# action name
name: test-github-workflows

on:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'

jobs:
# https://dev.to/harisharavindan/github-action-for-commit-message-validation-5b36 use markplace action
  commit-message:
    runs-on: ubuntu-latest
    name: commit-message-validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: commit_check
        uses: uptownaravi/verify-commit-message-action@v2
        with:
          regex: '#NORUN(.*)'

      - name: Run Trivy vulnerability scanner in repo mode
        if: #steps.trivy.outputs.exit-code == '1'       如果commit check失败了，执行下面的代码
        id: trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          output: 'trivy-report.txt'
          exit-code: '1'        ## when severity is critical ,exit-code is 1
          severity: CRITICAL  
         
    
      - name: Trivy failed slack send notification
        if: steps.trivy.outputs.exit-code == '1'
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload-file-path: ${{ steps.trivy.outputs.output }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}



  docker:
    runs-on: ubuntu-latest
    if: jobs.run_trivy.outputs.exit-code == '0'

    permissions:
      contents: read
      packages: write
      id-token: write # needed for signing

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        id: build-and-push
        with:
          push: true
          tags: willhit/go-fortune:${{ github.sha }} ## need change
          
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1

      - name: Sign image with a key
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY "${TAGS}@${DIGEST}"
        env:
          TAGS: ${{ github.sha }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ github.sha }}
        run: cosign sign --yes "${TAGS}@${DIGEST}"


      - name: send slack
        id: slack_success
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: "CHANNEL_ID" ## chenage channel id
          payload: |
            {
              "Name": "Hai Xinjie",
              "attachments": [
                {
                  "Matriculation number": "test",
                  "Email": "dbab09",
                  "fields": [
                    {
                      "Name": "ab",
                      "Matriculation number": "test",
                      "Email": abc@gmail.com,
                      "Repository": "In Progress",
                      "Docker Hub URL": "https://docker.com"
                    }
                  ]
                }
              ]
            }

        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}

